apiVersion: v1
kind: Service
metadata:
  name: lb-frontend
  namespace: sock-shop
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  type: LoadBalancer
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
