name: Deploy Kubernetes Manifests

on:
  push:
    paths:
      - 'manifests/**'
  workflow_run:
    workflows: ["EKS Deployment"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update Kubeconfig
      run: aws eks update-kubeconfig --name barchilon-eks-cluster --region us-west-2

    - name: Setup Kubectl
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy each manifest
      run: |
        kubectl apply -f manifests/serviceaccount.yaml
        kubectl apply -f manifests/complete-demo.yaml
        kubectl apply -f manifests/lb-frontend.yaml
