name: Deploy Kubernetes Manifests

on:
  push:
    paths:
      - 'manifests/**'
  workflow_run:
    workflows: ["EKS Deployment"]
    types:
      - completed

jobs:
  deploy-manifests:
    runs-on: ubuntu-latest
    environment: aws

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Configure kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Update Kubeconfig
      run: aws eks update-kubeconfig --name barchilon-eks-cluster --region us-west-2

    - name: Deploy each manifest
      run: |
        kubectl apply -f manifests/serviceaccount.yaml
        kubectl apply -f manifests/complete-demo.yaml
        kubectl apply -f manifests/lb-frontend.yaml
