name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCES_KEY_ID }} --profile default
          aws configure set aws_secret_acess_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default      

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: ./

      - name: Terraform Apply Helm Provider
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: ./

      - name: Terraform Output
        run: terraform output
        working-directory: ./
