name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.3

      - name: Terraform Init
        env:
          ACCESS_KEY : ${{ secrets.ACCESS_KEY }}
          SECRET_KEY : ${{ secrets.SECRET_KEY }}
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=main.tf
        working-directory: ./

      - name: Terraform Apply Helm Provider
        run: terraform apply -auto-approve -var-file=helm_provider.tf
        working-directory: ./

      - name: Terraform Output
        run: terraform output
        working-directory: ./
